#!/bin/bash
read_disk(){
	fdiskOUTPUT=$(echo $password | sudo -S fdisk -l)
		rm -rf /tmp/ReadDisk;
		while read -r line;
		do
		
		#find out whether the line at character 5th to 10th which is being read start with /dev/
		if [[ "${line:5:10}" == /dev/* ]] ;
		then
			
			#filter the line by looking for commas and take the pre-line number 1 and change all spaces that output into underscore and put it into file at /tmp/ReadDisk
			var=$(echo "$line" | awk -F',' '{printf $1}' | sed -e 's/ /_/g');
			alldisks=$(echo $alldisks $var);
		fi
		done <<< "$fdiskOUTPUT" 
	echo "$alldisks"
}

get_password(){
    while true;
	do
		password=$(kdialog --title "កម្មវិធីឈូស SD Card" --password "សូមបញ្ចូលលេខកូដសម្ងាត់សម្រាប់ ${USER}:");
		echo $password | sudo -S true
		if [[ $? -eq 1 ]];
		then
			kdialog --title "កម្មវិធីឈូស SD Card" --sorry "លេខកូដអ្នកមិនត្រឹមត្រូវ ឬអ្នកមិនមានសិទ្ធជា root\n\nសូមពិនិត្យថាអ្នកមានបានវាយលេខកូដត្រឹមត្រូវ និងមានសិទ្ធជា root គ្រប់គ្រាន់ជាមុនសិន មុនពេលបន្ត";
			kdialog --title "កម្មវិធីឈូស SD Card" --warningyesno "តើអ្នកចង់បញ្ឈប់ត្រឹមនេះឬទេ?";
            if [[ $? -eq 0 ]];
            then
                continue_status=false
                break
            fi
		else
			break
		fi
	done

}

get_sdcard(){

    while true;
    do
        selected_disk=$(kdialog --title "កម្មវិធីឈូស SD Card" --combobox "សូមជ្រើសរើស SD Card ដែលអ្នកចង់ឈូស\n\nចំណាំ៖ សូមជ្រើសរើសអោយបានត្រឹមត្រូវ" $(echo $(read_disk $password)))

        if [[ $? -eq 1 ]];
        then
            kdialog --title "កម្មវិធីឈូស SD Card" --sorry "សូមអ្នកជ្រើសរើស SD Card អោយបានត្រឹមត្រូវ"
            kdialog --title "កម្មវិធីឈូស SD Card" --warningyesno "តើអ្នកចង់បញ្ឈប់ត្រឹមនេះឬទេ?"
            if [[ $? -eq 0 ]];
            then
                continue_status=false
                break
            fi
        else
			kdialog --title "កម្មវិធីឈូស SD Cardg" --yesno "តើអ្នកបានជ្រើសរើស SD Card ត្រឹមត្រូវហើយឬនៅ?\n\nបញ្ចាក់៖ ប្រសិនបើជ្រើសរើសមិនត្រឹមត្រូវ វានឹងនាំឪ្យខូចប្រព័ន្ធប្រត្តិបត្តិអ្នកភ្លាមៗ";
			if [[ $? -eq 1 ]];
            then
                continue_status=false
                break
            fi
            break
        fi
    done
}

get_file(){
	while true;
	do
		selected_file=$(kdialog --title "ជ្រើសរើស File Boot" --getopenfilename /home/$USER);

		if [[ $? -eq 1 ]];
		then
            kdialog --title "កម្មវិធីឈូស SD Card" --sorry "សូមអ្នកជ្រើសរើស File Boot អោយបានត្រឹមត្រូវ"
            kdialog --title "កម្មវិធីឈូស SD Card" --warningyesno "តើអ្នកចង់បញ្ឈប់ត្រឹមនេះឬទេ?"
            if [[ $? -eq 0 ]];
            then
                continue_status=false
                break
            fi
        else
			kdialog --title "កម្មវិធីឈូស SD Cardg" --yesno "តើអ្នកបានជ្រើសរើស File Boot ត្រឹមត្រូវហើយឬនៅ?\n\nបញ្ចាក់៖ ប្រសិនបើជ្រើសរើសមិនត្រឹមត្រូវ វានឹងនាំឪ្យ Boot មិនដើរ";
			if [[ $? -eq 1 ]];
            then
                continue_status=false
                break
            fi
            break
        fi


	done
}

kdialog --title "កម្មវិធីឈូស SD Card" --msgbox "សូមស្វាគមន៍មកកាន់កម្មវិធីឈូស SD Card\n\nសូមចុច OK ដើម្បីបន្ត"
continue_status=true
while $continue_status -eq true;
do
	get_password
    if ! $continue_status;
    then
        break
    fi

    get_sdcard
    if ! $continue_status;
    then
        break
    fi

	get_file
	if ! $continue_status;
    then
        break
    fi

	dbusRef=`kdialog --title "កម្មវិធីឈូស SD Card" --progressbar "កំពុងចាប់ផ្តើម" 5`

	sdcard=$(echo $selected_disk | sed -e 's/_/ /g' | awk -F' ' '{printf $2}' | awk -F':' '{printf $1}')

	qdbus $dbusRef Set "" value 1
	qdbus $dbusRef setLabelText "កំពុងចែក Partition នៅលើ SD Card"

	echo $password | sudo -S umount "$sdcard""1" &>/dev/null
	echo $password | sudo -S umount "$sdcard""2" &>/dev/null

	echo $password | sudo -S parted $sdcard mklabel msdos --script
	echo $password | sudo -S parted $sdcard mkpart primary fat32 0% 106M --script
	echo $password | sudo -S parted $sdcard mkpart primary ext4 106M 80% --script
	echo $password | sudo -S parted $sdcard mkpart primary linux-swap 80% 100% --script

	qdbus $dbusRef Set "" value 2
	qdbus $dbusRef setLabelText "កំពុង Format Partition នៅលើ SD Card"

	echo $password | sudo -S mkfs.ext4 -F "$sdcard""2"
	echo $password | sudo -S mkfs.vfat -F32 "$sdcard""1"
	echo $password | sudo -S mkswap "$sdcard""3"

	rootuuid=$(ls -lah /dev/disk/by-uuid | grep $(echo "$sdcard""2" | awk -F'/' '{printf $3}') | awk -F' ' '{printf $9}')

	qdbus $dbusRef Set "" value 3
	qdbus $dbusRef setLabelText "កំពុង Mount Partitions នៅលើ SD Card"

	echo $password | sudo -S rm -rf /tmp/"$rootuuid"
	echo $password | sudo -S mkdir -p /tmp/"$rootuuid"
	echo $password | sudo -S mount "$sdcard""2" /tmp/"$rootuuid"
	echo $password | sudo -S mkdir /tmp/"$rootuuid"/boot
	echo $password | sudo -S mount "$sdcard""1" /tmp/"$rootuuid"/boot

	qdbus $dbusRef Set "" value 4
	qdbus $dbusRef setLabelText "កំពុងបញ្ចូលឯកសារចូល SD Card"

	if pp [[ "$selected_file" -eq "*.lz4" ]];
    then
	    ( pv "$selected_file" -f | sudo tar -C /tmp/"$rootuuid" -I lz4 -xpf- ) >/tmp/"$rootuuid"-log.txt 2>&1
    else 
        ( pv "$selected_file" -f | sudo tar -C /tmp/"$rootuuid" -xapf- ) >/tmp/"$rootuuid"-log.txt 2>&1
    fi

	qdbus $dbusRef Set "" value 5
	qdbus $dbusRef setLabelText "កំពុងរៀបចំបញ្ចប់ប្រត្តិបត្តិការ"

	sync

	echo $password | sudo -S umount "/tmp/$rootuuid/boot"
	echo $password | sudo -S umount "/tmp/$rootuuid"
	echo $password | sudo -S rm -rf /tmp/"$rootuuid"

	qdbus $dbusRef close

	kdialog --title "កម្មវិធីឈូស SD Card" --msgbox "ប្រត្តិបត្តិការណ៍បានជោគជ័យ"

	break

done
